name: Linting  # This can include other types of linting later on

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install

      # Get the list of changed files in the PR
      - name: Get list of changed files
        id: changed-files
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} > changed_files.txt
          cat changed_files.txt

      # Run linter only on changed JavaScript/TypeScript files
      - name: Run linter on changed JavaScript/TypeScript files
        run: |
          CHANGED_FILES=$(cat changed_files.txt | grep '\.js\|\.jsx\|\.ts\|\.tsx' || true)
          if [ -n "$CHANGED_FILES" ]; then
            echo "Linting the following files:"
            echo "$CHANGED_FILES"
            npx eslint $CHANGED_FILES
          else
            echo "No JavaScript/TypeScript files to lint."
          fi
