name: npm Audit

on:
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      - name: Run npm audit (Allow skipping unfixed vulnerabilities)
        run: npm audit
        continue-on-error: true  # Allow PR to pass even if vulnerabilities are found

      - name: Check for fixable vulnerabilities
        run: |
          npm audit --json > audit-report.json
          FIXABLE=$(grep -c '"fixAvailable": true' audit-report.json)
          if [ "$FIXABLE" -gt 0 ]; then
            echo "$FIXABLE fixable vulnerabilities found."
            exit 1  # Block PR if there are fixable vulnerabilities
          else
            echo "No fixable vulnerabilities found."
          fi
